### ISSUE TITLE
Search suggestions and Places results not rendering after upgrading Nightly

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#164]
The new popup UI rolled out to developer edition today, and with our addon installed you no longer see any search suggestions or results from Places.

<img width="1164" alt="screen shot 2016-04-29 at 7 28 40 pm" src="https://cloud.githubusercontent.com/assets/23885/14933085/c07c1d9c-0e40-11e6-94f9-1e7fd9b6e46c.png">

**Comment by chuckharmston** [comment]
A restart fixed this. I'll close for now, but will keep an eye out for STR.

**Comment by chuckharmston** [comment]
Reopening and marking as a blocker; this was reported in IRC by @cpeterso.

**Comment by jaredhirsch** [comment]
@pdehaan will try to find some good STR for this one :beers:

**Comment by jaredhirsch** [comment]
Aha! I've got this bug right now in my copy of dev edition.

I'm seeing some interesting errors in the console--both the old `this.mInput is null` errors from #138, as well as a new error: `window.universalSearch.urlbar is undefined`. Looks like the initialization code isn't completing.

I see the `loadIntoWindow start` console.log, but not the corresponding log for when it successfully completes. Examining the `window.universalSearch` object in the debugger, it looks like the object is partially initialized, as `urlbarPrefs` is assigned inside the `loadIntoWindow` method:

<img width="415" alt="screen shot 2016-05-02 at 5 38 16 pm" src="https://cloud.githubusercontent.com/assets/96396/14972028/23e0aa9e-108d-11e6-9f3f-cbfcf63efe1d.png">

**Comment by jaredhirsch** [comment]
OK, it looks like `_loadScripts` is failing because it can't find the `recommendation-server.js` file. WTF?

If I load the file manually in the browser toolbox debugger, it loads just fine.

Digging into why I'd get this `NS_ERROR_FILE_NOT_FOUND` error while loading scripts.

**Comment by jaredhirsch** [comment]
I'm able to reproduce this by downloading an older dev edition, then upgrading.

The popup doesn't work right after it is opened and closed once. I suspect the problem is related to our `popuphiding` handler. I was running into mind-bending bugs when investigating how JS and XBL event handlers interacted in #138. No errors are shown in the browser console when the bug occurs, which is a hallmark of an XBL bug (XBL mercilessly swallows errors).

STR below:

---

I downloaded an older version of dev edition (47.0a2, available on FTP [here](https://ftp.mozilla.org/pub/firefox/nightly/2016/04/2016-04-10-00-40-56-mozilla-aurora/)), here's what happened:
- Install old version of dev edition
- Start old version with add-on installed: looks fine, works fine
- Go to 'About Firefox' menu and click button to download latest, then click button to restart
- Start new version with add-on installed
- Before opening the popup, saw two interesting errors thrown by Gecko code (not by our add-on): the first warns about a deprecated search API, the second looks like a legit bug, a `ReferenceError` in `nsSearchService`:
  <img width="1044" alt="screen shot 2016-05-02 at 6 26 28 pm" src="https://cloud.githubusercontent.com/assets/96396/14972688/70f01bde-1093-11e6-8a03-813ce15302c3.png">

OK, it gets interesting when the popup is opened for the first time:
- Type 'f' in the urlbar, popup opens:

<img width="805" alt="screen shot 2016-05-02 at 7 11 51 pm" src="https://cloud.githubusercontent.com/assets/96396/14973218/ee5b5c18-1099-11e6-86f5-2b6f20112871.png">
- Type 'a' in the urlbar, search suggestions stream in, recommendation displays:

<img width="815" alt="screen shot 2016-05-02 at 7 11 57 pm" src="https://cloud.githubusercontent.com/assets/96396/14973220/f224585e-1099-11e6-8c5e-71f62ac9e8e6.png">
- Hit Escape, popup closes.
- Type 'x' in the urlbar, so the full string is now 'fax'. Popup opens with the same results from the first time it was opened:

<img width="809" alt="screen shot 2016-05-02 at 7 14 10 pm" src="https://cloud.githubusercontent.com/assets/96396/14973233/26471644-109a-11e6-8dec-1bb50c242a0d.png">

When the popup seems to be tall and empty, as in the description, it looks like the results from the first time the popup was closed are still there, but their `collapsed` attribute is set to `true`.

**Comment by jaredhirsch** [comment]
I think we might have multiple bugs here. Once I get clearer on the individual bugs, I'll break them off into separate bugs.

**Comment by jaredhirsch** [comment]
I can only reproduce one of the three bugs I saw yesterday. I can't reproduce the bug where `loadIntoWindow` never completes. I don't see the `nsSearchService` error or the deprecated search API warning.

The only bug I see currently is that the popup stops updating the results list after it's closed for the first time. Digging into this bug.

**Comment by jaredhirsch** [comment]
OK, I'm certain that, when the DOM gets frozen, the controller is working, and the connections between the input, popup, and controller seem OK. The issue must be in the DOM code.

I verified by running this loop in the browser toolbox console while I interacted with the urlbar:

``` js
function foo() {
  console.log('Update: ', Date.now());
  console.log('gURLBar.popup.mInput is ', gURLBar.popup.mInput);
  console.log('gURLBar.mController.input is ', gURLBar.mController.input);
  if (!STOP) { setTimeout(foo, 100); }
}
STOP = false;
foo();
```

I had to resort to logging in a loop because the controller is only connected to the input while the popup is open. For whatever reason, dev edition doesn't handle `setInterval` well in the browser toolbox (spews a bunch of events at once, then halts), but this periodic `setTimeout` approach worked fine.

**Comment by jaredhirsch** [comment]
Looks like the problem here is that `gURLBar.maxRows` is -1 for some odd reason.

When rows are going to be reused, the awesomebar updates a few rows at a time, up to `this.maxRows` (which is just a getter for the `gURLBar.maxRows` value). If maxRows is -1, the for loop never loops (it's initialized to i=0 as usual), which is why we don't see updates in the popup.

If I manually set `gURLBar.maxRows = 10` after the bug occurs, it's fixed.

We do have a binding that is applied to the urlbar, so that we can detect keypress events: https://github.com/mozilla/universal-search/blob/master/chrome/content/binding.xml#L33

I'm going to try to set maxRows there and see if it fixes the bug.

**Comment by jaredhirsch** [comment]
OK, so, there's some state juggling between `maxRows` and `gURLBar.popup._normalMaxRows` that happens when the popup is closed.

For some reason, the first time the popup closes, maxRows is set to -1. If I manually reset maxRows, it doesn't break again. One fix might be to manually do this in the popuphiding handler.

However, I think setting a popuphiding listener in JS is clobbering the XBL popuphiding handler defined in the parent binding. The better fix would be to move the popuphiding binding from JS to XBL.

I confirmed by logging in a loop:

``` js
STOP = false;
function foo() {
  console.log('gURLBar.maxRows is: ', gURLBar.maxRows);
  console.log('gURLBar._normalMaxRows is: ', gURLBar._normalMaxRows);
  console.log('gURLBar.popup.defaultMaxRows is: ', gURLBar.popup.defaultMaxRows);
  if (!STOP) { setTimeout(foo, 2000) }
}
```

**Comment by jaredhirsch** [comment]
The new dev edition came out just now (48.0a2 (2016-05-04)), and I can no longer reproduce this bug.

I might still land the popuphiding fix soon after public launch, but unless I can find a way to repro, this seems like it should not block.

**Comment by jaredhirsch** [comment]
Assigning to @chuckharmston to attempt to reproduce.

**Comment by pdehaan** [comment]
I'm unable to reproduce this in today's Developer Edition/Aurora build.
No matter how many times I seem to launch and dismiss the pop-up dialog, it looks fantastic!

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/15032551/f53273ae-1216-11e6-9314-bc82d0f8c662.png)

**Comment by jaredhirsch** [comment]
I think we can call this no longer a bug. We'll reopen if it reappears. I'll file a followup to change how we bind events like 'popuphiding' to avoid similar bugs in the future.

**Comment by jaredhirsch** [comment]
Reopening. Issue occurs when upgrading to today's Nightly `49.0a1 (2016-05-04)`.

In Nightly, the bug is fixed after a restart.

**Comment by cpeterso** [comment]
I still see this bug with Universal Search version 1.0.6 in Firefox Nightly 49.

**Comment by TDA** [comment]
@6a68 I still get this bug on 48-Beta.

**Comment by chuckharmston** [comment]
A few of reports of this still going on:

https://github.com/mozilla/universal-search/issues/254
https://github.com/mozilla/universal-search/issues/256

**Comment by jaredhirsch** [comment]
This should be fixed as of 1.0.9, which was released earlier this week.
