### ISSUE TITLE
Ensure search bar is restored on uninstall

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search#195]
Got a report of the search bar not being replaced when the addon is disabled.

It's possible this error is due to Tab Center breaking the Customize view, but it's also possible that restoring the search bar is broken.

**Comment by ghost** [comment]
I can reproduce this, if it helps

**Comment by chuckharmston** [comment]
I did a few tests on dev edition, OS X 10.11.4:
- Install current build of Universal Search, uninstall Universal Search: search restored.
- Install current build of Tab Center, install current build of Universal Search, uninstall Universal Search: search not restored.
- Install `HEAD` of Tab Center, install current build of Universal Search, uninstall Universal Search: search restored.

All the fail cases errored with `WindowWatcher code loading callback failed` and no exception.

These all point to the problem being with Tab Center (https://github.com/bwinton/VerticalTabs/issues/50), which is now fixed (https://github.com/bwinton/VerticalTabs/commit/ce272df548c04513f7c4121749aed893caf0f122).

@bwinton does this sound right to you?

**Comment by bwinton** [comment]
Yeah, I'ld believe that…

**Comment by chuckharmston** [comment]
@bwinton would it be a bother to ask you to update the build on Test Pilot to include this fix? It'd be nice to confirm that it fixes this bug before closing.

**Comment by bwinton** [comment]
Can it wait until tonight?  I'ld like to try getting the metrics uploading in before I cut a new release…

**Comment by chuckharmston** [comment]
@bwinton Sure thing! If you wouldn't mind pinging me when that happens, I'll check right away. <3

**Comment by bwinton** [comment]
@chuckharmston Ping!  (I just pushed 1.15, so check for updates, and probably restart, and give it another try!)

(Sorry about the late ping.  I _was_ hoping I could get some metrics in, but it looks like those won't be reviewed until tomorrow…)

**Comment by chuckharmston** [comment]
Confirmed: Tab Center 1.15 fixes this issue. Closing!

Thanks @bwinton!

**Comment by mlennon3** [comment]
I still have this issue, installed Test Pilot yesterday and I can't get my search bar back when disabling Universal Search and Test Pilot
